# Generated by Django 2.2.2 on 2019-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='dob',
            field=models.DateField(default='2000-08-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=20),
            preserve_default=False,
        ),
    ]
