# Generated by Django 2.2.2 on 2019-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0002_auto_20190623_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierge',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
