# Generated by Django 2.2.2 on 2019-06-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Actors.Concierge')),
                ('booked_for', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Actors.Tourist')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('resturant', 'Resturant'), ('travel', 'Travel')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_location', models.CharField(max_length=100)),
                ('initial_location', models.CharField(max_length=100)),
                ('travel_mode', models.CharField(choices=[('airplane', 'Airplane'), ('bus', 'Bus')], max_length=20)),
                ('ticket_no', models.CharField(max_length=100)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('no_of_people', models.IntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Booking')),
                ('resturant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place')),
            ],
        ),
        migrations.CreateModel(
            name='HostelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms', models.IntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Booking')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place')),
            ],
        ),
    ]
