# Generated by Django 2.2.2 on 2019-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelBooking',
            new_name='HotelBooking',
        ),
        migrations.RenameModel(
            old_name='ResturantBooking',
            new_name='RestaurantBooking',
        ),
        migrations.RenameField(
            model_name='restaurantbooking',
            old_name='resturant',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('travel', 'Travel')], max_length=20),
        ),
    ]
