# Generated by Django 2.2.2 on 2019-06-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20190623_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='no_of_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='travel_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Actors.Concierge'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Actors.Tourist'),
        ),
    ]
