# Generated by Django 2.2.2 on 2019-06-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20190624_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place'),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place'),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Place'),
        ),
    ]
